name: Publish
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/chechout@v3

      - name: Setup .NET
        uses: actions/seyup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./ClientDashboard_API/ClientDashboard_API.sln

      - name: Build
        run: dotnet build ./ClientDashboard_API/ClientDashboard_API.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./ClientDashboard_API/ClientDashboard_API.sln --configuration Release --no-build
